export const appConfig = {
  terminal: {
    // xterm 历史输出保留行数，限制缓冲区避免长时间日志输出导致内存持续增长。
    scrollbackRows: 2000,
  },
  sftp: {
    transfer: {
      // 全局传输并发上限：上传、下载、服务器间传输共享该队列。
      // 调大后会同时打开更多 SFTP/SSH 连接，可能增加服务器和本机压力。
      maxConcurrentTasks: 1,
    },
    textEditor: {
      // 大于该体积的远程文件不允许直接编辑，避免一次性读取导致卡顿或内存压力。
      maxEditableFileSizeBytes: 10 * 1024 * 1024,
      // 文本类型探测只读取文件头部固定字节，减少大文件检测开销。
      textProbeSampleBytes: 8192,
      // 命中这些扩展名时直接允许打开编辑器，其余文件会走内容探测。
      editableExtensions: [
        ".txt",
        ".md",
        ".markdown",
        ".log",
        ".csv",
        ".tsv",
        ".json",
        ".jsonc",
        ".xml",
        ".yaml",
        ".yml",
        ".toml",
        ".ini",
        ".conf",
        ".config",
        ".env",
        ".properties",
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".mjs",
        ".cjs",
        ".vue",
        ".svelte",
        ".html",
        ".htm",
        ".css",
        ".scss",
        ".sass",
        ".less",
        ".py",
        ".java",
        ".c",
        ".h",
        ".cpp",
        ".cc",
        ".cxx",
        ".hpp",
        ".cs",
        ".go",
        ".rs",
        ".php",
        ".rb",
        ".swift",
        ".kt",
        ".kts",
        ".dart",
        ".lua",
        ".pl",
        ".r",
        ".sh",
        ".bash",
        ".zsh",
        ".fish",
        ".bat",
        ".cmd",
        ".ps1",
        ".sql",
      ],
      // 无扩展名或点文件按完整文件名识别。
      editableFileNames: [
        ".config",
        ".env",
        ".gitignore",
        ".gitattributes",
        ".editorconfig",
        ".npmrc",
        ".yarnrc",
        ".prettierrc",
        ".eslintrc",
        ".babelrc",
        ".dockerignore",
        "dockerfile",
        "makefile",
        "cmakelists.txt",
        "package.json",
        "tsconfig.json",
        "vite.config.ts",
        "webpack.config.js",
      ],
    },
    imagePreview: {
      // 常见浏览器可直接预览的图片后缀，命中后文件树优先展示预览操作。
      extensions: [
        ".png",
        ".jpg",
        ".jpeg",
        ".gif",
        ".webp",
        ".bmp",
        ".ico",
        ".svg",
        ".avif",
      ],
      // 预览会把图片转为 data URL，限制体积避免大图一次性占用过多内存。
      maxPreviewFileSizeBytes: 10 * 1024 * 1024,
    },
    download: {
      // fastGet 使用并发读取，吞吐通常明显高于普通 stream pipe。
      fastGetConcurrency: 32,
      // 单次读取块大小，适当增大可减少高吞吐下载时的小块读写开销。
      fastGetChunkSizeBytes: 256 * 1024,
      // 进度刷新节流，避免下载过程中频繁 IPC 影响传输速度。
      progressIntervalMs: 500,
    },
  },
} as const;
